### ISSUE TITLE
Nuevas características

### ISSUE THREAD

**Issue by robsoncardosoti** [jortilles/EDA#2]
hola, me gusto mucho el proyecto.  ¿La fuente de datos es compatible con el servidor SQL y la interfaz internacionalizada?  Soy brasileño y me gustaría traducir al portugués.

**Comment by jortilles** [comment]
Hola.
Muchas gracias por el interes.
Todavia no esta internacionalizado. Pero en cuanto lo hagamos te lo haré
saber.
Saludos

**Comment by robsoncardosoti** [comment]
No pude conectarme a ninguna base de datos en esta versión de Docker. ¿Hay alguna configuración adicional para hacer?
¿El proyecto acepta contribuciones? ¿Desea conectarse a SQL Server y parece que todavía no está implementado?

**Comment by jortilles** [comment]
Hola.

El proyecto esta en fase beta. Estamos dando los primeros pasos.

De momento se conecta a Postgres y MySQL. SQLServer no está implementado
todavía.

Si que aceptamos contribuciones. Aunque tenemos que ver cómo lo hacemos.

En los próximos dias sacaremos una versión nueva.  Si quieres conectar a
SQL Server puedes esponsorizar ese desarrollo o contribuir con esa parte
del código.

Saludos Cordiales.

Juanjo Ortilles

**Comment by robsoncardosoti** [comment]
En la versión de Docker no pude conectarme a Postgres. MySql no está disponible. ¿Es esto solo funcional en la versión que todavía estará disponible?
Intentaré contribuir a la conexión de SQL Server y veré cómo agregar al código principal.

**Comment by jortilles** [comment]
o.k.

Pero quizás espera a la nueva versión. Han cambiado cosas y  no quisiera
hacerte trabajar en codigo antiguo.

Te aviso cuando actualize los repositorios.

Saludos Cordiales.
Juanjo Ortilles

**Comment by robsoncardosoti** [comment]
Hola, 
Creo que terminé la implementación para conectarme a MSSql.  ¿Actualizará el código en los próximos días?  ¿Cómo prefiere recibir la implementación?

**Comment by jortilles** [comment]
Hola!

Primero de todo, gracias! Es una muy grata sorpresa.

Estamos haciendo pruebas y tengo previsto actualizar el código durante la
semana que viene.

Espera a que actualicemos el código y lo integramos.

Puedes hacer un pull request una vez se haya actualizado. Recuerda que te
comenté que habría cambios....

Saludos Cordiales.

Juanjo Ortilles

**Comment by robsoncardosoti** [comment]
Sí, lo recuerdo.  Ya estoy trabajando en la internacionalización.  Creo que será necesario hablar de esto.

**Comment by jortilles** [comment]
Hola.
Espera... espera. El lunes o martes subiremos una nueva versión.

Saludos Cordiales.

Juanjo Ortilles

**Comment by jortilles** [comment]
Hola @robsoncardosoti  ya hemos hecho el update. 

Haz un pull request si quieres con la integración de SqlServer

**Comment by robsoncardosoti** [comment]
No pude ejecutar la nueva versión. Está mostrando algunos errores. 
Por ejemplo: "Property 'describeData' does not exist on type 'ChartUtilsService'." y "Error: Cannot find module './src/routes/RoutesLoader'"
Pero vi que el código para conectarse a la base de datos fue cambiado. Intentaré volver a implementar y, cuando esté listo, enviaré lo "pull request".

Para la internacionalización nativa de angular es necesario actualizar a la versión 9 debido al texto presente en el código typescript. ¿Hay algún plan de actualización para angular 9?

**Comment by jortilles** [comment]
si... las cadenas de conexión ala bbdd han cambiado.  porque he dejado las
del docker....  restaura las anteriorres... lo corregiré en cuanto pueda.



Saludos Cordiales.

Juanjo Ortilles

**Comment by alexjortilles** [comment]
Hola @robsoncardosoti 

Soy uno de los programadores de este proyecto, me gustaria comentar sobre el tema de la internacionalización... 

Podriamos hablar lo por email o hacer videollamada? (Entiendo que hablas espanyol)

Saludos.

**Comment by robsoncardosoti** [comment]
Hola Alex,
Sería mejor por correo electrónico (robsoncardoso.ti@gmail.com), ya que no es mi idioma nativo.
