### ISSUE TITLE
Implement the ability to embed a dashboard in view-only mode

### ISSUE THREAD

**Issue by marpontes** [jortilles/EDA#4]
As a systems integrator, it would be nice to use EDA as a source of embedded analytics from which I'd easily discover insights and make them available on a portal via Iframe.

The ideal embedded dashboard would be a view-only without side menos and editing controls. 

That mode could be enabled by a queryparam via url such as `http://demoeda.jortilles.com/#/dashboard/5e9d5d81281a56295afd9cd9/?mode=view`

**Comment by jortilles** [comment]
At this moment we have "public dashboards" witch is the starting of that path. 

Take a look at: http://demoeda.jortilles.com/#/public/5e89b7fc7118d543b283d573

We need to enable SSO and dashboards parameters to get to the point you mentione. But  we have the path.
