### ISSUE TITLE
Cross table amb possibilitat d'escollir els camps a les files i columnes.

### ISSUE THREAD

**Issue by jordiisidro** [jortilles/EDA#57]
M'aniria bé la possibilitat de poder triar quins camps estan a les files i columnes en una cross table.
Ara només permet un camp per les files i la resta a les columnes.

També aniria bé poder plegar i desplegar les dimensions triades.

**Comment by jortilles** [comment]
Amb la nova versió d'EDA aixo ja es possible. (el punt 1 )
