### ISSUE TITLE
Default login fails

### ISSUE THREAD

**Issue by jwillmer** [jortilles/EDA#7]
Setup:
![image](https://user-images.githubusercontent.com/1503577/93303249-7a5d2c80-f7fb-11ea-8759-85897ca0cb59.png)

Docker log:
![image](https://user-images.githubusercontent.com/1503577/93303276-821cd100-f7fb-11ea-9c03-a24bebf4504a.png)

Credentials:
![image](https://user-images.githubusercontent.com/1503577/93303344-9bbe1880-f7fb-11ea-81c9-48355ec962fa.png)

Output:
![image](https://user-images.githubusercontent.com/1503577/93303375-a4aeea00-f7fb-11ea-9e90-6aed545f9da0.png)

**Comment by jortilles** [comment]
Hi. 
Yes... we just saw it....
We are rolling out a new release. It will solve this issue... We'll inform you asap

**Comment by jortilles** [comment]
Hi jwillmer  
We just  released the new version. 1.4.  
Now it is multi language. So, you don't need an specific docker for english version. 

Just try:  docker run -p 80:80 jortilles/eda:latest
